version: '3.8'

services:
  postgresql_provider_ecommerce:
    image: postgres:15
    container_name: postgresql_provider_library_v2
    ports:
      - "5434:5432"
    volumes:
      - db_provider_management_service:/var/lib/postgresql/data
#    restart: unless-stopped
    environment:
      - POSTGRES_DB=finalproject
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6380:6379"
    restart: always
volumes:
  db_provider_management_service:
    driver: local