server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6380
  application:
    name: FinalProjectREST
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: ${DB_URL:jdbc:postgresql://localhost:5434/finalproject}

  jpa:
    show-sql: true
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    generate-ddl: true
    hibernate:
      ddl-auto: update
